site_name: 'WPLib Box'
site_url: 'http://wplib.org/docs/'
docs_dir: 'mkdocs'
site_dir: 'docs'
repo_name: 'WPLib Box'
repo_url: 'https://github.com/wplib/wplib-docs'
use_directory_urls: false
theme:
   name: 'material'
   palette:
      primary:pink
      accent:blue

   feature:
      tabs: true

extra:
  social:
    - type: 'github'
      link: 'https://github.com/wplib'
    - type: 'twitter'
      link: 'https://twitter.com/wplib'

markdown_extensions:
  - pymdownx.details
  - pymdownx.mark
  - admonition
  - meta
  - footnotes
  - sane_lists
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true


pages:
  - 'Home': 'index.md'
  - 'FAQ': 'faq.md'
  - 'Glossary': 'glossary.md'
  - 'Troubleshooting': 'troubleshooting.md'
  - 'Roadmap': 'roadmap.md'
  - 'Philosophy': 'philosophy.md'
  - 'Team': 'team.md'
  - 'Support': 'support.md'
  - 'About': 'about.md'
  - 'Quick Start':
    - 'Getting Started': 'quick-start/index.md'
  - 'How To':
    - 'Overview': 'how-to/index.md'
    - 'Initial Setup':
        - 'Overview': 'how-to/setup/index.md'
        - 'Directories': 'how-to/setup/directories.md'
        - 'Hostname': 'how-to/setup/hostname.md'
    - 'Box CLI': 'how-to/box-command.md'
    - 'Composer': 'how-to/composer.md'
    - 'MkDocs': 'how-to/mkdocs.md'
    - 'PHP': 'how-to/processvm.md'
    - 'Servers': 'how-to/servers.md'
    - 'WP CLI': 'how-to/wp-cli.md'
    - 'Tutorials':
        - 'Host Entries': 'how-to/tutorials/host-entries.md'
        - 'Secure Shell': 'how-to/tutorials/secure-shell.md'
        - 'Terminal': 'how-to/tutorials/terminal.md'
  - 'Components':
    - 'Overview': 'components/index.md'
  - 'Architecture':
    - 'Overview': 'architecture/index.md'
    - 'Projects':
        - 'Overview': 'architecture/projects/index.md'
        - 'project.json': 'architecture/projects/project.json.md'
    - 'Stacks': 'architecture/stacks.md'
    - 'Components': 'architecture/components.md'
  - 'GitHub':
    - 'Overview': 'github/index.md'
  - 'Download':
    - 'Downloading': 'download/index.md'


