site_name: 'WPLib Box'
site_url: 'http://wplib.org/docs/'
docs_dir: 'mkdocs'
site_dir: 'docs'
repo_name: 'WPLib Box'
repo_url: 'https://github.com/wplib/wplib-docs'
use_directory_urls: false
theme:
   name: 'material'
   palette:
      primary:pink
      accent:blue

   feature:
      tabs: true

extra:
  social:
    - type: 'github'
      link: 'https://github.com/wplib'
    - type: 'twitter'
      link: 'https://twitter.com/wplib'

markdown_extensions:
  - pymdownx.details
  - pymdownx.mark
  - admonition
  - meta
  - footnotes
  - sane_lists
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true


pages:
  - 'Home': 'index.md'
  - 'FAQ': 'faq.md'
  - 'Glossary': 'glossary.md'
  - 'Troubleshooting': 'troubleshooting.md'
  - 'Roadmap': 'roadmap.md'
  - 'Philosophy': 'philosophy.md'
  - 'Team': 'team.md'
  - 'Support': 'support.md'
  - 'About': 'about.md'
  - 'Quick Start':
    - 'Getting Started': 'quick-start/index.md'
  - 'Using':
    - 'Overview': 'using/index.md'
    - 'Initial Setup':
        - 'Overview': 'using/setup/index.md'
        - 'Directories': 'using/setup/directories.md'
        - 'Hostname': 'using/setup/hostname.md'
    - 'Box CLI': 'using/box-command.md'
    - 'Composer': 'using/composer.md'
    - 'MkDocs': 'using/mkdocs.md'
    - 'PHP': 'using/processvm.md'
    - 'project.json': 'using/project.json.md'
    - 'Servers': 'using/servers.md'
    - 'WP CLI': 'using/wp-cli.md'
    - 'Tutorials':
        - 'Host Entries': 'using/tutorials/host-entries.md'
        - 'Secure Shell': 'using/tutorials/secure-shell.md'
        - 'Terminal': 'using/tutorials/terminal.md'
    - 'Architecture':
        - 'Overview': 'using/architecture/index.md'
  - 'Projects':
    - 'Overview': 'projects/index.md'
  - 'Stacks':
    - 'Overview': 'stacks/index.md'
  - 'Components':
    - 'Overview': 'components/index.md'
  - 'GitHub':
    - 'Overview': 'github/index.md'
  - 'Download':
    - 'Downloading': 'download/index.md'


